### ISSUE TITLE
Error Conflicts Allocation Pool IP

### ISSUE THREAD

**Issue by yuzukiseo** [nolsatuid/courses#3]
Assalamualaikum.

Ini ceritanya mau ngulang tugas dari awal karena screenshoot kurang besar, dan akhirnya smua tak delete dari awal, termasuk networknya.

nah ini mau coba lagi dari awal, tp pas mau create network malah muncul error confilicts allocation pool ip.

Detail pesan errornya:

> Error: Failed to create subnet "10.9.9.1/24" for network "pod9-management": Gateway ip 10.9.9.1 conflicts with allocation pool 10.9.9.1-10.9.9.100. Neutron server returns request_ids: ['req-32c8ab93-22a0-4d00-9879-bf7ce4827c93']

Mohon bantuanya.

Terima kasih dan wassalamualaikum.

**Comment by ragilsetian** [comment]
itu konflik pool subnetnya mas. ip gateway janga di include ke pool subnet. Silahkan bisa di edit. semoga membantu

**Comment by yuzukiseo** [comment]
Ok mas sudah solved.

Thanks.
